#' Function to get format the data for the statistical analysis
#'
#' Given the \code{data.frame} output generated by the \code{allFilesInOne} function
#' generates as output a \code{data.frame} where each row represent a patient and
#' each column will represent each of the variables of interest for this study.
#'
#' @param integrated_df The data.frame generated by the \code{allFilesInOne} function.
#' @param raceAvailable Value will be \code{TRUE} for the sites collecting this variable.
#' @param dir.input The path where the 2.2 MISC cohort files are located.
#' @param verbose By default \code{FALSE}. Change it to \code{TRUE} to get an on-time log from the function.
#' @return An object of class \code{data.frame} formatted to perform statistical analysis and to generate table 1.
#' @examples
#'
#' formatted_output <- format_data_for_stats(
#'               integrated_df = misc_complete,
#'               raceAvailable,
#'               dir.input,
#'               verbose
#'              )
#' @export format_data_for_stats
#'

format_data_for_stats <- function( integrated_df, raceAvailable, dir.input, verbose ){

  currSiteId <- unique( integrated_df$siteid )

  mainTable <- integrated_df %>%
    dplyr::filter( n_hospitalisation == 1 ) %>%
    dplyr::select( patient_num, date, variant_misc, len_hospitalisation, age, sex, in_icu, dead ) %>%
    dplyr::group_by( patient_num, date, variant_misc, len_hospitalisation, age, sex ) %>%
    dplyr::summarise( in_icu = max( in_icu ),
                      dead = max( dead ))

  if( raceAvailable == TRUE ){
    race_raw <- read.delim(file.path(dir.input, "/LocalPatientRace.csv"), sep = ",", skip = 0)
    mainTable <- left_join( mainTable, race_raw %>% select( patient_num, race_4ce), by="patient_num")
  }

  ### add other variables present in the clinical characteristic table
  clinicalCharact <- read.delim(system.file(paste0("extdata", .Platform$file.sep,
                                                 "clinicalCharacteristics.txt"), package = "FourCePhase2.2MISC"), stringsAsFactors = FALSE)
  clin_var <- integrated_df %>%
    filter( n_hospitalisation == 1 &
              concept_code %in% clinicalCharact$concept_code ) %>%
    left_join( clinicalCharact, by = "concept_code") %>%
    mutate( value = 1 ) %>%
    #select( patient_num, concept_code, variableName, value) %>%
    select( patient_num, variableName, value) %>%
    unique()

  clin_var2merge <- clin_var %>%
    spread(key = variableName, value =  value, fill = 0)

  ### add the new variables and
  mainTable <- mainTable %>%
    dplyr::left_join( clin_var2merge, by = "patient_num") %>%
    replace(is.na(.), 0)

  ## any non-present variable as empty column all with 0
  varsNoPatients <- clinicalCharact %>%
    dplyr::select( variableName ) %>%
    unique( ) %>%
    dplyr::filter(! variableName %in% colnames( mainTable ))

  for( i in 1:length( varsNoPatients$variableName )){
    mainTable[ varsNoPatients$variableName[i]] <- 0
  }
  ## Add a column called cardiovascular outcome
  # logic to fill this new colum: it will be a 1 if the patient has
  # Cardiovascular outcome: SICARDIAC OR/AND Shock related ICD-10 code AND/OR ECMO  AND/OR CARDIAC ARREST AND/OR CPR
  mainTable <- mainTable %>%
    dplyr::mutate( cardiovascular_outcome = ifelse( SICARDIAC == 1 | Shock == 1| ECMO == 1 | `Cardiac arrest` == 1 | CPR == 1, 1, 0)) %>%
    unique()

  ## some rows are duplicated in the main table with different values for in_icu, how should we deal with this?
  #if the patient was any day during the first hospitalization in the icu then it should be 1?


  return( mainTable )


}
