#' Function to get table 3 summary for outcomes

#' Given the \code{data.frame} output generated by the \code{allFilesInOne} function
#' generates as output the table 3 for the manuscript
#'
#' @param complete_df The data.frame generated by the \code{allFilesInOne} function.
#' @param obfuscation_threshold FALSE if no obfuscation is needed, the numeric value when there is obfuscation
#' @param dir.input The path where the 2.2 MISC cohort files are located.
#' @param currSiteId Site ID
#' @param verbose By default \code{FALSE}. Change it to \code{TRUE} to get an on-time log from the function.
#' @return Table 3 for the manuscript.
#' @examples
#'
#' t3 <- misc_table3(
#'               complete_df,
#'               currSiteId,
#'               obfuscation_threshold,
#'               verbose
#'              )
#' @export misc_table3
#'
#'
#'
misc_table3 <- function(complete_df, obfuscation_threshold, currSiteId, dir.input, dir.output, raceAvailable, verbose){

  outcomeVar <- read.delim('inst/extdata/outcomeVariables.txt')
  total_n_patients <- length(unique(complete_df$patient_num))

  mainTable <- complete_df %>%
    filter( n_hospitalisation == 1 ) %>%
    select( patient_num, variant_misc, len_hospitalisation, age, sex, in_icu, dead ) %>%
    unique() %>%
    group_by( patient_num ) %>%
    mutate( in_icu = ifelse( sum( in_icu )>=1, 1, 0),
            dead = ifelse( sum( dead )>=1, 1, 0)) %>%
    ungroup() %>%
    select( patient_num, variant_misc, len_hospitalisation, age, sex, in_icu, dead ) %>%
    unique()

  #add race if available
  if( raceAvailable == TRUE ){
    race_raw <- read.delim(file.path(dir.input, "/LocalPatientRace.csv"), sep = ",", skip = 0)
    mainTable <- left_join( mainTable, race_raw %>% select( patient_num, race_4ce), by="patient_num")
  }

  clin_var <- complete_df %>%
    filter( concept_code %in% outcomeVar$concept_code ) %>%
    left_join( outcomeVar, by = "concept_code") %>%
    mutate( value = 1 ) %>%
    select( patient_num,category, value) %>%
    unique() %>%
    spread(key = category, value =  value, fill = 0) %>%
    unique() %>%
    group_by( patient_num ) %>%
    summarise(across(everything(), sum)) %>%
    unique()


  ### add the new variables and
  mainTable <- mainTable %>%
    dplyr::left_join( clin_var, by = "patient_num") %>%
    replace(is.na(.), 0)

  # do not add in non-present variables, because you cannot run fisher test on these
  ## any non-present variable as empty column all with 0
  #varsNoPatients <- outcomeVar %>%
  #  dplyr::select( category ) %>%
  #  unique( ) %>%
  #  dplyr::filter(! category %in% colnames( mainTable ))

  #if( length( varsNoPatients$category) != 0){
  #  for( i in 1:length( varsNoPatients$category )){
  #    mainTable[ varsNoPatients$category[i]] <- 0
  #  }
  #}


  ## Add a column called cardiovascular outcome
  # logic to fill this new colum: it will be a 1 if the patient has
  # Cardiovascular outcome: Composite adverse cardiovascular outcome category or dead
  mainTable <- mainTable %>%
    dplyr::mutate( cardiovascular_outcome = ifelse( "Composite adverse cardiovascular outcome" == 1 | dead == 1 , 1, 0))

  outcomes <- c("in_icu", "dead", "Anticoagulation therapy", "Cardiac arrest",
                "Composite adverse cardiovascular outcome", "Coronary aneurysm","Diuretic therapy",
                "ECMO","Inotropic support","Invasive monitoring (arterial line)",
                "Oxygen supplementation","Sedation or muscle relaxant", "cardiovascular_outcome" )

  #re-pivot it
  long_table <- mainTable %>%
    tidyr::pivot_longer(
      cols = colnames(mainTable)[colnames(mainTable) %in% outcomes],
      names_to = "categories",
      values_to = "value")



  ## estimate the p-value (fisher test)
  fisherTest <- long_table %>%
    group_by( categories ) %>%
    mutate( n_distinct_values = length(unique( value )),
            p.value =ifelse( n_distinct_values > 1, round( fisher.test( value, variant_misc )$p.value, 3), NA)) %>%
    select( categories, p.value ) %>%
    unique()

  ## estimate the N and percentage per category
  counts_percentages <- long_table %>%
    group_by( variant_misc ) %>%
    mutate(total_n = n_distinct(patient_num)) %>%
    filter( value == 1 ) %>%
    group_by(categories, variant_misc) %>%
    summarise(n = n_distinct(patient_num),
              n_obfuscated = ifelse( n > obfuscation_threshold | isFALSE( obfuscation_threshold), n, 0.5),
              perc = (n_obfuscated / total_n) * 100) %>%
    unique() %>%
    select(-n_obfuscated)

  counts_percentages_total <- long_table %>%
    filter( value == 1 ) %>%
    group_by(categories ) %>%
    summarise(n = n_distinct(patient_num),
              n_obfuscated = ifelse( n > obfuscation_threshold | isFALSE( obfuscation_threshold), n, 0.5),
              perc = (n_obfuscated / total_n_patients) * 100) %>%
    unique() %>%
    select(-n_obfuscated) %>%
    mutate( variant_misc = "total")

  #combine both
  counts_percentages_combined <- rbind(counts_percentages, counts_percentages_total )

  # pivot counts_percentages with combined n / percentage cells
  output_table3_with_stats <- counts_percentages_combined %>%
    mutate(n_perc = paste0(n, ' (', round(perc, digits = 2), '%)')) %>%
    select(-n, -perc) %>%
    unique() %>%
    tidyr::pivot_wider(names_from = variant_misc, values_from = n_perc, values_fill = '0 (0%)') %>%
    left_join( fisherTest )

  # order rows
  ordered_rows <- outcomes

  # reorder combined df
  output_table3_with_stats <- output_table3_with_stats %>%
    # this ensures the variables which were not able to be done with the fisher test are included
    right_join(data.frame('categories' = ordered_rows)) %>%
    filter( categories %in% ordered_rows ) %>%
    mutate(categories =  factor(categories, levels = ordered_rows)) %>%
    arrange(categories)

  # change NA by 0 (0%)
  output_table3_with_stats[ is.na( output_table3_with_stats$Alpha ), ]$Alpha <- "0 (0%)"
  output_table3_with_stats[ is.na( output_table3_with_stats$Delta ), ]$Delta <- "0 (0%)"
  output_table3_with_stats[ is.na( output_table3_with_stats$Omicron ), ]$Omicron <- "0 (0%)"
  output_table3_with_stats[ is.na( output_table3_with_stats$total ), ]$total <- "0 (0%)"

  # add n to column names
  colnames_df <- mainTable %>%
    group_by(variant_misc) %>%
    summarise(N = n_distinct(patient_num)) %>%
    ungroup()
  colnames_df <- rbind(colnames_df, data.frame('variant_misc' = 'Total', 'N' = sum(colnames_df$N)))
  colnames_df <- colnames_df %>%
    mutate(pasted_names = paste0(variant_misc, ' (n = ', N, ')'))

  colnames(output_table3_with_stats)[c(2,3,4,5)] <- colnames_df$pasted_names

  # export table
  write.table(output_table3_with_stats, paste0(dir.output, currSiteId, '_table3.txt'), sep = "\t", quote = FALSE, row.names = FALSE)

  # return the final output table
  return( mainTable )


}
