#' Function to get table 1 categorical variables

#' Given the \code{data.frame} output generated by the \code{allFilesInOne} function
#' generates as output the table 1 for the manuscript for categorical variables
#'
#' @param complete_df The data.frame generated by the \code{allFilesInOne} function.
#' @param obfuscation_threshold FALSE if no obfuscation is needed, the numeric value when there is obfuscation
#' @param currSiteId Site ID
#' @param verbose By default \code{FALSE}. Change it to \code{TRUE} to get an on-time log from the function.
#' @return Table 1 categorical variables for the manuscript.
#' @examples
#'
#' t1_cat <- misc_table1_cat(
#'               complete_df,
#'               currSiteId,
#'               obfuscation_threshold,
#'               verbose
#'              )
#' @export misc_table1_cat
#'
#'
#'
misc_table1_cat <- function(complete_df, obfuscation_threshold, currSiteId, dir.output, raceAvailable, verbose){

  clinicalChar <- read.delim('inst/extdata/clinicalCharacteristics.txt')
  total_n_patients <- length(unique(complete_df$patient_num))

  mainTable <- complete_df %>%
    filter( n_hospitalisation == 1 ) %>%
    select( patient_num, variant_misc, len_hospitalisation, age, sex, in_icu, dead ) %>%
    unique() %>%
    group_by( patient_num ) %>%
    mutate( in_icu = ifelse( sum( in_icu )>=1, 1, 0),
            dead = ifelse( sum( dead )>=1, 1, 0)) %>%
    ungroup() %>%
    select( patient_num, variant_misc, len_hospitalisation, age, sex, in_icu, dead ) %>%
    unique()

  #add race if available
  if( raceAvailable == TRUE ){
    mainTable <- left_join( mainTable, race_raw %>% select( patient_num, race_4ce), by="patient_num")
  }

  clin_var <- complete_df %>%
    filter( concept_code %in% clinicalChar$concept_code ) %>%
    left_join( clinicalChar, by = "concept_code") %>%
    mutate( value = 1 ) %>%
    select( patient_num, concept_code, category, value) %>%
    unique() %>%
    spread(key = category, value =  value, fill = 0) %>%
    select( -concept_code) %>%
    unique() %>%
    group_by( patient_num ) %>%
    summarise(across(everything(), sum)) %>%
    unique()


  ### add the new variables and
  mainTable <- mainTable %>%
    dplyr::left_join( clin_var, by = "patient_num") %>%
    replace(is.na(.), 0)

  ## any non-present variable as empty column all with 0
  varsNoPatients <- clinicalChar %>%
    dplyr::select( category ) %>%
    unique( ) %>%
    dplyr::filter(! category %in% colnames( mainTable ))

  if( length( varsNoPatients$category) != 0){
    for( i in 1:length( varsNoPatients$category )){
      mainTable[ varsNoPatients$category[i]] <- 0
    }
  }



  #re-pivot it
  long_table <- mainTable %>%
    tidyr::pivot_longer(
      cols = c("in_icu", "dead",   "asthma", "Cardiac arrest", "Cardiovascular symptoms", "COVID-19", "generalized symptoms",
               "GI symptoms","Kawasaki","Liver involvement","Neurologic symptoms","obesity_overweight","Renal involvement",
               "Respiratory symptoms" ),
      names_to = "categories",
      values_to = "value")




  ## estimate the p-value (fisher test)
  fisherTest <- long_table %>%
    group_by( categories ) %>%
    mutate( p.value =round( fisher.test( value, variant_misc )$p.value, 3) ) %>%
    select( categories, p.value ) %>%
    unique()

  ## estimate the N and percentage per category
  counts_percentages <- long_table %>%
    group_by( variant_misc ) %>%
    mutate(total_n = n_distinct(patient_num)) %>%
    filter( value == 1 ) %>%
    group_by(categories, variant_misc) %>%
    summarise(n = n_distinct(patient_num),
              n_obfuscated = ifelse( n > obfuscation_threshold | isFALSE( obfuscation_threshold), n, 0.5),
              perc = (n_obfuscated / total_n) * 100) %>%
    unique() %>%
    select(-n_obfuscated)

  counts_percentages_total <- long_table %>%
    filter( value == 1 ) %>%
    group_by(categories ) %>%
    summarise(n = n_distinct(patient_num),
              n_obfuscated = ifelse( n > obfuscation_threshold | isFALSE( obfuscation_threshold), n, 0.5),
              perc = (n_obfuscated / total_n_patients) * 100) %>%
    unique() %>%
    select(-n_obfuscated) %>%
    mutate( variant_misc = "total")

  #combine both
  counts_percentages_combined <- rbind(counts_percentages, counts_percentages_total )

  # pivot counts_percentages with combined n / percentage cells
  output_table1_cat_with_stats <- counts_percentages_combined %>%
    mutate(n_perc = paste0(n, ' (', round(perc, digits = 2), '%)')) %>%
    select(-n, -perc) %>%
    unique() %>%
    tidyr::pivot_wider(names_from = variant_misc, values_from = n_perc, values_fill = '0 (0%)') %>%
    left_join( fisherTest )

  # export table
  write.csv(output_table1_cat_with_stats, paste0(dir.output, currSiteId, '_table1_cat.csv'), quote = FALSE, row.names = FALSE)

  # return the final output table
  return( output_table3_with_stats )


}
