#' Function to estimate number of MISC patients by period
#'
#' Given the \code{data.frame} output generated by the \code{allFilesInOne} function
#' and given a specific period, generates as output a \code{data.frame} with MISC
#' cases.
#'
#' @param integrated_df The data.frame generated by the \code{allFilesInOne} function.
#' @param period The counts can be done by weeks, months or year. By default it is done by month.
#' @param obfuscation_threshold FALSE if no obfuscation is needed, the numeric value when there is obfuscation
#' @param output_plot By default \code{FALSE}. Change it to \code{TRUE} to get a barplot output.
#' @param output_df By default \code{TRUE}. Change it to \code{FALSE} to not to get the counts as a data.frame.
#' @param dir.output The path to the output directory where the aggregate counts and plots will be saved.
#' @param verbose By default \code{FALSE}. Change it to \code{TRUE} to get an on-time log from the function.
#' @return An object of class \code{data.frame} with the counts, and the plot when output_plot is set to TRUE.
#' @examples
#'
#' casesCounts <- misc_cases_perTimePeriod(
#'               integrated_df = misc_complete,
#'               period = "month",
#'               output_plot = FALSE,
#'               output_df   = TRUE,
#'               dir.output
#'              )
#' @export misc_cases_perTimePeriod
#'

misc_cases_perTimePeriod <- function( integrated_df, period = "month", obfuscation_threshold = obfuscation, output_plot = FALSE, output_df = TRUE, dir.output, verbose ){

  #check that the period value is one of the allowed ones
  if( period %in% c("weeks", "month", "year")){
    print(paste0("Grouping by ", period))
  }else{
    print("period values not correct. the only allowed values are: weeks, month and year")
    stop()
  }

  currSiteId <- unique( integrated_df$siteid )

    if( period == "month"){
    misc_cases <- integrated_df %>%
      dplyr::group_by( month ) %>%
      dplyr::summarise( distinct_patients = ifelse( length(unique(patient_num)) > obfuscation_threshold | isFALSE( obfuscation_threshold), length(unique(patient_num)), 0.5))
  }else if( period == "year"){
    misc_cases <- integrated_df %>%
      dplyr::group_by( year ) %>%
      dplyr::summarise( distinct_patients = ifelse( length(unique(patient_num)) > obfuscation_threshold | isFALSE( obfuscation_threshold), length(unique(patient_num)), 0.5))
  }else if( period == "week"){
    misc_cases <- integrated_df %>%
      dplyr::group_by( weeks ) %>%
      dplyr::summarise( distinct_patients = ifelse( length(unique(patient_num)) > obfuscation_threshold | isFALSE( obfuscation_threshold), length(unique(patient_num)), 0.5))
  }
  colnames(misc_cases)[1] <- 'period'


  if( output_plot == TRUE ){
    ### plot barplot
    misc_counts_plot <- ggplot2::ggplot(data=misc_cases, aes(x=period, y=distinct_patients)) +
      geom_bar(stat="identity") +
      ggtitle(paste0("MISC patients per ", period )) +
      ylab("Number of distinct MISC patients") + xlab(paste0("By ", period )) +
      theme_bw() +
      theme(plot.title = element_text(hjust = 0.5))

    ggplot2::ggsave(filename=file.path(dir.output,paste0('/figures/',currSiteId, "_MISCpatientCounts_per", period, ".png")),plot=print(misc_counts_plot))

  }


  # if( output_df == TRUE ){
  #   ## Save the generated file with the counts as part of the outputs
  #   write.table( x         = misc_cases,
  #                file      = file.path(dir.output,paste0('/QC/',currSiteId, "_MISCpatientCounts_per", period, ".txt")),
  #                col.names = TRUE,
  #                row.names = FALSE,
  #                quote     = FALSE,
  #                sep       = "\t" )
  # }

  ## as sanity check and for reference generate table with number of patients per variant
  total_misc_per_variant <- integrated_df %>%
    dplyr::group_by( variant_misc ) %>%
    dplyr::summarise( distinct_patients = ifelse( length(unique(patient_num)) > obfuscation_threshold | isFALSE( obfuscation_threshold), length(unique(patient_num)), 0.5))

  print( total_misc_per_variant )

  # write.table( x         = total_misc_per_variant,
  #              file      = file.path(dir.output,paste0('/QC/',currSiteId, "_total_misc_per_variant.txt")),
  #              col.names = TRUE,
  #              row.names = FALSE,
  #              quote     = FALSE,
  #              sep       = "\t" )
}
