#' Function to get table 2 summary for laboratory values of patients with MIS-C

#' Given the \code{data.frame} output generated by the \code{allFilesInOne} function
#' generates as output the table 2 for the manuscript
#'
#' @param complete_df The data.frame generated by the \code{allFilesInOne} function.
#' @param obfuscation_threshold FALSE if no obfuscation is needed, the numeric value when there is obfuscation
#' @param currSiteId Site ID
#' @param verbose By default \code{FALSE}. Change it to \code{TRUE} to get an on-time log from the function.
#' @return Table 2 for the manuscript.
#' @examples
#'
#' t2 <- misc_table2(
#'               complete_df,
#'               currSiteId,
#'               obfuscation_threshold,
#'               verbose
#'              )
#' @export misc_table2
#'
#'
#'

misc_table2 <- function(complete_df, currSiteId, obfuscation_threshold, dir.output, verbose){

  labs_of_interest <- read.delim(system.file(paste0("extdata", .Platform$file.sep,
                                                    "laboratoryCharacteristics.txt"), package = "FourCePhase2.2MISC"), stringsAsFactors = FALSE)

  atAdmission_per_variant <- complete_df %>%
    dplyr::filter( n_hospitalisation == 1 & days_since_admission == 0 ) %>%
    dplyr::filter( concept_type == "LAB-LOINC" ) %>%
    dplyr::left_join(labs_of_interest, by = 'concept_code') %>%
    dplyr::filter( ! is.na( variableName )) %>%
    dplyr::group_by( variableName, variant_misc, patient_num ) %>%
    dplyr::mutate( selected_value = ifelse( worstValue == "lowest", min( value), max(value ))) %>%
    dplyr::ungroup( ) %>%
    dplyr::select(patient_num, variableName, units, selected_value, variant_misc ) %>%
    unique() %>%
    dplyr::filter( ! is.na(value),
                   value != -999 ) %>%
    #dplyr::mutate( selected_value = ifelse( selected_value == -999, NA, selected_value )) %>%
    dplyr::group_by( variableName, variant_misc ) %>%
    dplyr::mutate( median_value = round( median(selected_value, na.rm = TRUE), 2),
                   iqr_value = round( IQR(selected_value, na.rm = TRUE), 2),
                   mean_value =  round( mean(selected_value, na.rm = TRUE), 2),
                   sd_value = round( sd(selected_value, na.rm = TRUE), 2),
                   min_value = round( min( selected_value, na.rm = TRUE), 2),
                   max_value = round( max( selected_value, na.rm = TRUE), 2),
                   n_patients = n_distinct(patient_num)) %>%
    dplyr::select( variant_misc, variableName,  units, median_value, iqr_value, mean_value, sd_value, min_value, max_value, n_patients) %>%
    unique()


  atAdmission_total <- complete_df %>%
    dplyr::filter( n_hospitalisation == 1 & days_since_admission == 0 ) %>%
    dplyr::filter( concept_type == "LAB-LOINC" ) %>%
    dplyr::left_join(labs_of_interest, by = 'concept_code') %>%
    dplyr::filter( ! is.na( variableName )) %>%
    dplyr::group_by( variableName, patient_num ) %>%
    dplyr::mutate( selected_value = ifelse( worstValue == "lowest", min( value), max(value ))) %>%
    dplyr::ungroup( ) %>%
    dplyr::select(patient_num, variableName, units, selected_value, variant_misc ) %>%
    unique() %>%
    dplyr::filter( ! is.na(value),
                   value != -999 ) %>%
    #dplyr::mutate( selected_value = ifelse( selected_value == -999, NA, selected_value )) %>%
    dplyr::group_by( variableName) %>%
    dplyr::mutate( variant_misc = "total_n",
                   median_value = round( median(selected_value, na.rm = TRUE), 2),
                   iqr_value = round( IQR(selected_value, na.rm = TRUE), 2),
                   mean_value =  round( mean(selected_value, na.rm = TRUE), 2),
                   sd_value = round( sd(selected_value, na.rm = TRUE), 2),
                   min_value = round( min( selected_value, na.rm = TRUE), 2),
                   max_value = round( max( selected_value, na.rm = TRUE), 2),
                   n_patients = n_distinct(patient_num)) %>%
    dplyr::select( variant_misc, variableName,  units, median_value, iqr_value, mean_value, sd_value, min_value, max_value, n_patients) %>%
    unique()

  atAdmission <- rbind( atAdmission_per_variant, atAdmission_total )

  #### save as RData for meta-analysis
  save(atAdmission, file = paste0(dir.output, "/table2AtAdmission.RData") )

  #### during admission
  duringAdmission_per_variant <- complete_df %>%
    dplyr::filter( n_hospitalisation == 1 ) %>%
    dplyr::filter( concept_type == "LAB-LOINC" ) %>%
    dplyr::left_join(labs_of_interest, by = 'concept_code') %>%
    dplyr::filter( ! is.na( variableName )) %>%
    dplyr::group_by( patient_num, variableName ) %>%
    dplyr::mutate(  selected_value = ifelse( worstValue == "lowest", min( value ), max( value ) ) ) %>%
    dplyr::ungroup( ) %>%
    dplyr::select(patient_num, variableName, units, selected_value, variant_misc ) %>%
    unique() %>%
    dplyr::filter( ! is.na(value),
                   value != -999 ) %>%
    #dplyr::mutate( selected_value = ifelse( selected_value == -999, NA, selected_value )) %>%
    dplyr::group_by( variableName, variant_misc ) %>%
    dplyr::mutate( median_value = round( median(selected_value, na.rm = TRUE), 2),
                   iqr_value = round( IQR(selected_value, na.rm = TRUE), 2),
                   mean_value =  round( mean(selected_value, na.rm = TRUE), 2),
                   sd_value = round( sd(selected_value, na.rm = TRUE), 2),
                   min_value = round( min( selected_value, na.rm = TRUE), 2),
                   max_value = round( max( selected_value, na.rm = TRUE), 2),
                   n_patients = n_distinct(patient_num)) %>%
    dplyr::select( variant_misc, variableName,  units, median_value, iqr_value, mean_value, sd_value, min_value, max_value, n_patients) %>%
    unique()


  duringAdmission_total <- complete_df %>%
    dplyr::filter( n_hospitalisation == 1 ) %>%
    dplyr::filter( concept_type == "LAB-LOINC" ) %>%
    dplyr::left_join(labs_of_interest, by = 'concept_code') %>%
    dplyr::filter( ! is.na( variableName )) %>%
    dplyr::group_by( patient_num, variableName ) %>%
    dplyr::mutate(  selected_value = ifelse( worstValue == "lowest", min( value ), max( value ) ) ) %>%
    dplyr::ungroup( ) %>%
    dplyr::select(patient_num, variableName, units, selected_value, variant_misc ) %>%
    unique() %>%
    dplyr::filter( ! is.na(value),
                   value != -999 ) %>%
    #dplyr::mutate( selected_value = ifelse( selected_value == -999, NA, selected_value )) %>%
    dplyr::group_by( variableName ) %>%
    dplyr::mutate( variant_misc = "total_n",
                   median_value = round( median(selected_value, na.rm = TRUE), 2),
                   iqr_value = round( IQR(selected_value, na.rm = TRUE), 2),
                   mean_value =  round( mean(selected_value, na.rm = TRUE), 2),
                   sd_value = round( sd(selected_value, na.rm = TRUE), 2),
                   min_value = round( min( selected_value, na.rm = TRUE), 2),
                   max_value = round( max( selected_value, na.rm = TRUE), 2),
                   n_patients = n_distinct(patient_num)) %>%
    dplyr::select( variant_misc, variableName,  units, median_value, iqr_value, mean_value, sd_value, min_value, max_value, n_patients) %>%
    unique()

  duringAdmission <- rbind( duringAdmission_per_variant, duringAdmission_total )

  #### save as RData for meta-analysis
  save(duringAdmission, file = paste0(dir.output, "/table2DuringAdmission.RData") )

  ### pivot it
  atAdmission_output <- atAdmission %>%
    mutate( output_value = paste0('median: ', median_value, ' IQR(', iqr_value, ')',
                                  'mean: ', mean_value, ' SD(', sd_value, ')',
                                  '[', min_value, ' , ', max_value, ']',
                                  ' patients: ', ifelse( n_patients > obfuscation_threshold | isFALSE( obfuscation_threshold), n_patients, 0.5))) %>%
    select(-median_value, -iqr_value, -mean_value, -sd_value, -min_value, -max_value, -n_patients )%>%
    tidyr::pivot_wider( names_from = variant_misc,
                        values_from = output_value)

  atAdmission_output$time_point <- "At admission day 0"


  duringAdmission_output <- duringAdmission %>%
     mutate( output_value = paste0('median: ', median_value, ' IQR(', iqr_value, ')',
                             'mean: ', mean_value, ' SD(', sd_value, ')',
                             '[', min_value, ' , ', max_value, ']',
                             ' patients: ', ifelse( n_patients > obfuscation_threshold | isFALSE( obfuscation_threshold), n_patients, 0.5))) %>%
    select(-median_value, -iqr_value, -mean_value, -sd_value, -min_value, -max_value, -n_patients )%>%
    tidyr::pivot_wider( names_from = variant_misc,
                        values_from = output_value)

  duringAdmission_output$time_point <- "During hospitalization"

  output_table2 <- rbind( atAdmission_output, duringAdmission_output )

  ### sort it as the word table 2
  ordered_rows <- c( "white blood cell count (Leukocytes)", "lymphocyte",
                     "neutrophil","platelets","albumin","d_dimer","prothrombin time (PT)",
                     "fibrinogen", "ferritin","alanine aminotransferase (ALT)",
                     "aspartate aminotransferase (AST)", "creatinine","troponin",
                     "CRP")

  # reorder combined df
  output_table2 <- output_table2 %>%
    mutate(variableName =  factor(variableName, levels = ordered_rows)) %>%
    arrange(variableName)

  # if the data does not contain all variants, add in the columns here
  if(!'Alpha' %in% colnames(output_table2)){output_table2$Alpha <- NA}
  if(!'Delta' %in% colnames(output_table2)){output_table2$Delta <- NA}
  if(!'Omicron' %in% colnames(output_table2)){output_table2$Omicron <- NA}


  # estimate the p-value
  stats_kruskal_atAdmission <- complete_df %>%
    dplyr::filter( n_hospitalisation == 1 & days_since_admission == 0 ) %>%
    dplyr::filter( concept_type == "LAB-LOINC" ) %>%
    dplyr::left_join(labs_of_interest, by = 'concept_code') %>%
    dplyr::filter( ! is.na( variableName )) %>%
    dplyr::group_by( variableName, variant_misc, patient_num ) %>%
    dplyr::mutate( selected_value = ifelse( worstValue == "lowest", min( value), max(value ))) %>%
    dplyr::ungroup( ) %>%
    dplyr::group_by( variableName )

  # only estimate the p-value if at least 2 variant groups are present.
  if(n_distinct(complete_df$variant_misc) >= 2){
    stats_kruskal_atAdmission <- stats_kruskal_atAdmission %>%
    do(tidy(kruskal.test(x = .$selected_value, g = .$variant_misc)))
    stats_kruskal_atAdmission$time_point <- "At admission day 0"


  }else{
    stats_kruskal_atAdmission$p.value <- NA
    stats_kruskal_atAdmission$time_point <- "At admission day 0"

  }


  stats_kruskal_duringAdmission <- complete_df %>%
    dplyr::filter( n_hospitalisation == 1 ) %>%
    dplyr::filter( concept_type == "LAB-LOINC" ) %>%
    dplyr::left_join(labs_of_interest, by = 'concept_code') %>%
    dplyr::filter( ! is.na( variableName )) %>%
    dplyr::group_by( patient_num, variableName ) %>%
    dplyr::mutate(  selected_value = ifelse( worstValue == "lowest", min( value ), max( value ) ) ) %>%
    dplyr::select(patient_num, variableName, units, selected_value, variant_misc ) %>%
    unique() %>%
    dplyr::group_by( variableName )

  # only estimate the p-value if at least 2 variant groups are present.
  if(n_distinct(complete_df$variant_misc) >= 2){
    stats_kruskal_duringAdmission <- stats_kruskal_duringAdmission %>%
    do(tidy(kruskal.test(x = .$selected_value, g = .$variant_misc)))
    stats_kruskal_duringAdmission$time_point <- "During hospitalization"

  }else{
    stats_kruskal_duringAdmission$p.value <- NA
    stats_kruskal_duringAdmission$time_point <- "During hospitalization"

  }

  stats_kruskal <- rbind( stats_kruskal_atAdmission, stats_kruskal_duringAdmission) %>%
    mutate( statistic = round( statistic, 3),
            p.value   = round( p.value, 3)) %>%
    select( variableName, statistic, p.value, time_point )

  output_table2_with_stats <- left_join( output_table2, stats_kruskal, by=c("variableName", "time_point"))

  ## add n to column names
  colnames_df <- complete_df %>%
    group_by(variant_misc) %>%
    summarise(N = n_distinct(patient_num)) %>%
    ungroup()
  if(!'Alpha' %in% colnames_df$variant_misc){colnames_df <- rbind(colnames_df, data.frame('variant_misc' = 'Alpha', 'N' = 0))}
  if(!'Delta' %in% colnames_df$variant_misc){colnames_df <- rbind(colnames_df, data.frame('variant_misc' = 'Delta', 'N' = 0))}
  if(!'Omicron' %in% colnames_df$variant_misc){colnames_df <- rbind(colnames_df, data.frame('variant_misc' = 'Omicron', 'N' = 0))}
  colnames_df <- rbind(colnames_df, data.frame('variant_misc' = 'Total', 'N' = sum(colnames_df$N)))
  colnames_df <- colnames_df %>%
    mutate(pasted_names = paste0(variant_misc, ' (n = ', N, ')'))

  # reorder columns
  output_table2_with_stats <- output_table2_with_stats %>%
    select(variableName, units, Alpha, Delta, Omicron, total_n, time_point)

  colnames(output_table2_with_stats)[c(3,4,5,6)] <- colnames_df$pasted_names

  write.table(output_table2_with_stats, paste0(dir.output, currSiteId, '_table2.txt'), sep="\t", quote = FALSE, row.names = FALSE)

  # return the final output table
  return( output_table2_with_stats )

}
