#' Function to get table 1 summary for MISC patients during the MISC hospitalization

#' Given the \code{data.frame} output generated by the \code{format_data_for_stats} function
#' generates as output the table 1 for the manuscript
#'
#' @param formated_df The data.frame generated by the \code{format_data_for_stats} function.
#' @param obfuscation_threshold FALSE if no obfuscation is needed, the numeric value when there is obfuscation
#' @param currSiteId Site ID
#' @param dir.output The path to the output directory where the aggregate counts and plots will be saved.
#' @param verbose By default \code{FALSE}. Change it to \code{TRUE} to get an on-time log from the function.
#' @return Table 1 for the manuscript.
#' @examples
#'
#' t1 <- misc_table1(
#'               formated_df,
#'               currSiteID,
#'               dir.output,
#'               verbose
#'              )
#' @export misc_table1
#'
misc_table1 <- function( formated_df, obfuscation_threshold, currSiteId, dir.output, verbose ){

  formated_df$sex           <- factor(formated_df$sex, levels=c("male", "female"), labels=c("Male", "Female"))
  formated_df$variant_misc  <- factor(formated_df$variant_misc)
  formated_df$race_4ce      <- factor(formated_df$race_4ce,
                                      levels=c("white", "black", "asian", "american_indian", "other", "n_information"),
                                      labels=c("White", "Black", "Asian", "American indian", "Other", "Not Available"))
  formated_df$in_icu  <- as.logical(formated_df$in_icu == 1)
  formated_df$dead    <- as.logical(formated_df$dead == 1)
  formated_df$Shock   <- as.logical(formated_df$Shock == 1)
  formated_df$ECMO    <- as.logical(formated_df$ECMO == 1)
  formated_df$SICARDIAC <- as.logical(formated_df$SICARDIAC == 1)
  formated_df$CPR       <- as.logical(formated_df$CPR == 1)

  formated_df$cardiovascular_outcome  <- as.logical(formated_df$cardiovascular_outcome == 1)
  formated_df$`Heart failure`         <- as.logical(formated_df$`Heart failure` == 1)
  formated_df$`Respiratory failure`   <- as.logical(formated_df$`Respiratory failure` == 1)
  formated_df$`Cardiac arrest`        <- as.logical(formated_df$`Cardiac arrest` == 1)

  label(formated_df$race_4ce) <- "Race"
  label(formated_df$age)      <- "Age"
  label(formated_df$sex)      <- "Sex"
  label(formated_df$in_icu)   <- "ICU"
  label(formated_df$variant_misc)   <- "Variant MIS-C"
  label(formated_df$cardiovascular_outcome) <- "Cardiovascular Outcome"
  label(formated_df$len_hospitalisation)    <- "Length of hospitalization (days)"

  misc_t1 <- table1::table1(~ age + sex + race_4ce + len_hospitalisation + in_icu + dead + cardiovascular_outcome + Shock + SICARDIAC + ECMO + `Heart failure` + `Cardiac arrest` + `Respiratory failure` | variant_misc,
                 data=formated_df )

  misc_t1_df <- as.data.frame(xml2::read_html(misc_t1) %>% rvest::html_table(fill=TRUE))


  ## Save the generated table 1
  #if( obfuscation_threshold == FALSE ){
  #  write.table( x         = misc_t1_df,
  #               file      = file.path(dir.output,paste0(currSiteId, "_misc_t1.txt")),
  #               col.names = TRUE,
  #               row.names = FALSE,
  #               quote     = FALSE,
  #               sep       = "\t" )
  }


  return( misc_t1 )
}


