#' Function to get table 1  variables

#' Given the \code{data.frame} output generated by the \code{allFilesInOne} function
#' generates as output the table 1 for the manuscript
#'
#' @param complete_df The data.frame generated by the \code{allFilesInOne} function.
#' @param dir.input The path where the 2.2 MISC cohort files are located.
#' @param obfuscation_threshold FALSE if no obfuscation is needed, the numeric value when there is obfuscation
#' @param currSiteId Site ID
#' @param verbose By default \code{FALSE}. Change it to \code{TRUE} to get an on-time log from the function.
#' @return Table 1 categorical variables for the manuscript.
#' @examples
#'
#' t1_cat <- misc_table1(
#'               complete_df,
#'               currSiteId,
#'               obfuscation_threshold,
#'               verbose
#'              )
#' @export misc_table1
#'
#'
#'
misc_table1 <- function(complete_df, obfuscation_threshold, currSiteId, dir.input, dir.output, raceAvailable, verbose){

  clinicalChar <- read.delim(system.file(paste0("extdata", .Platform$file.sep,
                                                    "clinicalCharacteristics.txt"), package = "FourCePhase2.2MISC"), stringsAsFactors = FALSE)

  # remove dots from ICD codes to make sure if matches with all the sites
  clinicalChar$concept_code <- gsub("[.]", "", clinicalChar$concept_code)

  total_n_patients <- length(unique(complete_df$patient_num))
  print(paste0("Total MISC patients used as denominator for table 1: ", total_n_patients))

  mainTable <- complete_df %>%
    filter( n_hospitalisation == 1 ) %>%
    select( patient_num, variant_misc, len_hospitalisation, age, sex, in_icu, dead ) %>%
    unique() %>%
    group_by( patient_num ) %>%
    mutate( in_icu = ifelse( sum( in_icu )>=1, 1, 0),
            dead = ifelse( sum( dead )>=1, 1, 0)) %>%
    ungroup() %>%
    select( patient_num, variant_misc, len_hospitalisation, age, sex, in_icu, dead ) %>%
    unique()

  print("main table created")

  #add race if available
  if( raceAvailable == TRUE ){
    race_raw <- read.delim(file.path(dir.input, "/LocalPatientRace.csv"), sep = ",", skip = 0)
    mainTable <- left_join( mainTable, race_raw %>% select( patient_num, race_4ce), by="patient_num")
  }

  # remove dots from ICD codes in complete_df if any
  complete_df$concept_code <- gsub( "[.]", "", complete_df$concept_code )
  # at category level
  clin_var_category <- complete_df %>%
    filter( concept_code %in% clinicalChar$concept_code ) %>%
    left_join( clinicalChar, by = "concept_code") %>%
    mutate( value = 1 ) %>%
    select( patient_num, category, value) %>%
    unique() %>%
    spread(key = category, value =  value, fill = 0) %>%
    unique() %>%
    group_by( patient_num ) %>%
    summarise(across(everything(), sum)) %>%
    unique()

  print("clin_var_category created")

  #at variable name level
  clin_var_variable_name <- complete_df %>%
    filter( concept_code %in% clinicalChar$concept_code ) %>%
    left_join( clinicalChar, by = "concept_code") %>%
    mutate( value = 1 ) %>%
    select( patient_num, variableName, value) %>%
    unique() %>%
    spread(key = variableName, value =  value, fill = 0) %>%
    unique() %>%
    group_by( patient_num ) %>%
    summarise(across(everything(), sum)) %>%
    unique()
  print("clin_var_variable_name created")

  # merge both
  clin_var <- merge( clin_var_category, clin_var_variable_name)

  ### add the new variables and
  mainTable <- mainTable %>%
    dplyr::left_join( clin_var, by = "patient_num") %>%
    replace(is.na(.), 0)

  ## any non-present variable as empty column all with 0
  varsNoPatients <- clinicalChar %>%
    dplyr::select( category ) %>%
    unique( ) %>%
    dplyr::filter(! category %in% colnames( mainTable ))

  if( length( varsNoPatients$category) != 0){
    for( i in 1:length( varsNoPatients$category )){
      mainTable[ varsNoPatients$category[i]] <- 0
    }
  }

  varsNoPatientsVarLevel <- clinicalChar %>%
    dplyr::select( variableName ) %>%
    unique( ) %>%
    dplyr::filter(! variableName %in% colnames( mainTable ))

  if( length( varsNoPatientsVarLevel$variableName) != 0){
    for( i in 1:length( varsNoPatientsVarLevel$variableName )){
      mainTable[ varsNoPatientsVarLevel$variableName[i]] <- 0
    }
  }


  vars_of_interest <- c("in_icu","dead",'overweight', 'obesity',
                    'fatigue_asthenia', 'rash_erythema',
                    'GI SYMPTOMS', 'abdominal pain', 'nausea_vomiting', 'diarrhea_enteritis_ileitis', 'apendicitis_peritonitis',
                    'RESPIRATORY SYMPTOMS', 'cough', 'rhinitis rhinorrhea', 'sore throat', 'tachypnea', 'dyspnea_shortness of breath',
                    'CARDIOVASCULAR SYMPTOMS', 'chest pain', 'palpitations', 'peripheral edema','hypotension', 'pre-syncope_syncope','ventricular dysfunction', 'heart failure', 'shock',
                    'NEUROLOGIC SYMPTOMS', 'headache', 'confusion', 'irritability', 'seizures', 'muscle weakness', 'encephalopathy_meningoencephalitis', 'lethargy', 'stroke',
                    'RENAL INVOLVEMENT', 'kidney dysfunction', 'acute renal failure',
                    'LIVER INVOLVEMENT', 'hepatitis or liver dysfunction', 'hepatic failure',
                    'Kawasaki')


  #re-pivot it
  long_table <- mainTable %>%
    tidyr::pivot_longer(
      cols = all_of(vars_of_interest),
      names_to = "categories",
      values_to = "value")

  print("long_table created")

  ## estimate the p-value (fisher test) if:
  ### - at least one value for the variant / category (n_distinct_subgroup)
  ### - at least 2 variants are present (variants_present)
  ### - not all the values are the same (n_distinct_values)
  variants_present <- n_distinct(long_table$variant_misc) >= 2
  fisherTest <- long_table %>%
    group_by(categories, variant_misc) %>%
    mutate(n_distinct_subgroup = length(unique(patient_num))) %>%
    ungroup() %>%
    group_by( categories ) %>%
    mutate( n_distinct_values = length(unique( value )),
            p.value = ifelse(  n_distinct_subgroup > 1 & n_distinct_values > 1 & variants_present, round( fisher.test( value, variant_misc )$p.value, 3), NA))%>%
    select( categories, p.value ) %>%
    unique()

  ## estimate the N and percentage per category
  counts_percentages <- long_table %>%
    group_by( variant_misc ) %>%
    mutate(total_n = n_distinct(patient_num)) %>%
    filter( value == 1 ) %>%
    group_by(categories, variant_misc) %>%
    summarise(n = n_distinct(patient_num),
              n_obfuscated = ifelse( n > obfuscation_threshold | isFALSE( obfuscation_threshold), n, 0.5),
              perc = (n_obfuscated / total_n) * 100) %>%
    unique() %>%
    select(-n_obfuscated)

  counts_percentages_total <- long_table %>%
    filter( value == 1 ) %>%
    group_by(categories ) %>%
    summarise(n = n_distinct(patient_num),
              n_obfuscated = ifelse( n > obfuscation_threshold | isFALSE( obfuscation_threshold), n, 0.5),
              perc = (n_obfuscated / total_n_patients) * 100) %>%
    unique() %>%
    select(-n_obfuscated) %>%
    mutate( variant_misc = "total")

  #combine both
  counts_percentages_combined <- rbind(counts_percentages, counts_percentages_total )

  # save the output as an RData file for meta-analysis before reformating
  counts_combined4meta = counts_percentages_combined %>%
    mutate( n = ifelse( n > obfuscation_threshold | isFALSE( obfuscation_threshold), n , 0.5)) %>%
    select( - perc )
  save(counts_combined4meta, file = paste0(dir.output, "/table1Categorical.RData") )

  # pivot counts_percentages with combined n / percentage cells
  output_table1_cat_with_stats <- counts_percentages_combined %>%
    mutate(n_perc = paste0(n, ' (', round(perc, digits = 2), '%)')) %>%
    select(-n, -perc) %>%
    unique() %>%
    tidyr::pivot_wider(names_from = variant_misc, values_from = n_perc, values_fill = '0 (0%)') %>%
    right_join( fisherTest )

  print("output_table1_cat_with_stats created")
  # order rows
  ordered_rows <- c('overweight', 'obesity',
                    'fatigue_asthenia', 'rash_erythema',
                    'GI SYMPTOMS', 'abdominal pain', 'nausea_vomiting', 'diarrhea_enteritis_ileitis', 'apendicitis_peritonitis',
                    'RESPIRATORY SYMPTOMS', 'cough', 'rhinitis rhinorrhea', 'sore throat', 'tachypnea', 'dyspnea_shortness of breath',
                    'CARDIOVASCULAR SYMPTOMS', 'chest pain', 'palpitations', 'peripheral edema','hypotension', 'pre-syncope_syncope','ventricular dysfunction', 'heart failure', 'shock',
                    'NEUROLOGIC SYMPTOMS', 'headache', 'confusion', 'irritability', 'seizures', 'muscle weakness', 'encephalopathy_meningoencephalitis', 'lethargy', 'stroke',
                    'RENAL INVOLVEMENT', 'kidney dysfunction', 'acute renal failure',
                    'LIVER INVOLVEMENT', 'hepatitis or liver dysfunction', 'hepatic failure',
                    'Kawasaki')

  # reorder combined df
  print(paste0("output_table1_cat_with_stats has ", nrow(output_table1_cat_with_stats), " number of rows"))
  print(paste0("the categories present in this table are: ", paste( output_table1_cat_with_stats$categories, collapse = "; ")))

  output_table1_cat_with_stats <- output_table1_cat_with_stats %>%
    filter( categories %in% ordered_rows ) %>%
    mutate(categories =  factor(categories, levels = ordered_rows)) %>%
    arrange(categories)


  # if the data does not contain all variants, add in the columns here
  if(!'Alpha' %in% colnames(output_table1_cat_with_stats)){output_table1_cat_with_stats$Alpha <- NA}
  if(!'Delta' %in% colnames(output_table1_cat_with_stats)){output_table1_cat_with_stats$Delta <- NA}
  if(!'Omicron' %in% colnames(output_table1_cat_with_stats)){output_table1_cat_with_stats$Omicron <- NA}


  # change NA by 0 (0%)
  output_table1_cat_with_stats[ is.na( output_table1_cat_with_stats$Alpha ), ]$Alpha <- "0 (0%)"
  output_table1_cat_with_stats[ is.na( output_table1_cat_with_stats$Delta ), ]$Delta <- "0 (0%)"
  output_table1_cat_with_stats[ is.na( output_table1_cat_with_stats$Omicron ), ]$Omicron <- "0 (0%)"
  output_table1_cat_with_stats[ is.na( output_table1_cat_with_stats$total ), ]$total <- "0 (0%)"


  ##### add the continuous variables estimation
  # add in continuous variables
  continuous_summary <- mainTable %>%
    select(patient_num, age, len_hospitalisation, variant_misc) %>%
    rename(orig_age = age,
           orig_len_hosp = len_hospitalisation) %>%
    group_by(variant_misc) %>%
    unique() %>%
    summarise(age = paste0('median: ', median(orig_age),
                           ', IQR: (', round(IQR(orig_age), digits = 2),
                           '), min,max: [', min(orig_age), ',', max(orig_age),
                           '], mean= ', round(mean(orig_age), digits = 2),
                           ', SD=', round(sd(orig_age), digits = 2)),
              length_hospitalization = paste0('median: ', median(orig_len_hosp),
                                              ', IQR: (', round(IQR(orig_len_hosp), digits = 2),
                                              '), min,max: [', min(orig_len_hosp), ',', max(orig_len_hosp),
                                              '], mean= ', round(mean(orig_len_hosp), digits = 2),
                                              ', SD=', round(sd(orig_len_hosp), digits = 2))) %>%
    t() %>%
    as.data.frame()
  colnames(continuous_summary) <- continuous_summary[1,]
  continuous_summary$variableName <- rownames(continuous_summary)
  rownames(continuous_summary) <- NULL
  continuous_summary <- continuous_summary[-1,]

  ## create a simplified version for the meta-analysis
  continuous_summary_for_meta_analysis <- mainTable %>%
    select(patient_num, age, len_hospitalisation, variant_misc) %>%
    rename(orig_age = age,
           orig_len_hosp = len_hospitalisation) %>%
    group_by(variant_misc) %>%
    unique() %>%
    summarise(age_median = median(orig_age),
              age_iqr    = round(IQR(orig_age), digits = 2),
              age_min = min(orig_age),
              age_max = max(orig_age),
              age_mean = round(mean(orig_age), digits = 2),
              age_sd   = round(sd(orig_age), digits = 2),
              length_hospitalization_median = median(orig_len_hosp),
              length_hospitalization_iqr    = round(IQR(orig_len_hosp), digits = 2),
              length_hospitalization_min = min(orig_len_hosp),
              length_hospitalization_max = max(orig_len_hosp),
              length_hospitalization_mean = round(mean(orig_len_hosp), digits = 2),
              length_hospitalization_sd   = round(sd(orig_len_hosp), digits = 2))

  continuous_summary_total_for_meta_analysis <- mainTable %>%
    select(patient_num, age, len_hospitalisation, variant_misc) %>%
    rename(orig_age = age,
           orig_len_hosp = len_hospitalisation) %>%
    unique() %>%
    summarise(age_median = median(orig_age),
              age_iqr    = round(IQR(orig_age), digits = 2),
              age_min = min(orig_age),
              age_max = max(orig_age),
              age_mean = round(mean(orig_age), digits = 2),
              age_sd   = round(sd(orig_age), digits = 2),
              length_hospitalization_median = median(orig_len_hosp),
              length_hospitalization_iqr    = round(IQR(orig_len_hosp), digits = 2),
              length_hospitalization_min = min(orig_len_hosp),
              length_hospitalization_max = max(orig_len_hosp),
              length_hospitalization_mean = round(mean(orig_len_hosp), digits = 2),
              length_hospitalization_sd   = round(sd(orig_len_hosp), digits = 2))
  continuous_summary_total_for_meta_analysis$variant_misc <- "total"
  continuous_summary_for_meta_analysis <- rbind( continuous_summary_for_meta_analysis, continuous_summary_total_for_meta_analysis)
  save(continuous_summary_for_meta_analysis, file = paste0(dir.output, "/table1Continuous.RData") )


  # find totals of the continuous variables
  continuous_total_summary <- mainTable %>%
    select(patient_num, age, len_hospitalisation) %>%
    rename(orig_age = age,
           orig_len_hosp = len_hospitalisation) %>%
    unique() %>%
    summarise(age = paste0('median: ', median(orig_age),
                           ', IQR: (', round(IQR(orig_age), digits = 2),
                           '), min,max: [', min(orig_age), ',', max(orig_age),
                           '], mean= ', round(mean(orig_age), digits = 2),
                           ', SD=', round(sd(orig_age), digits = 2)),
              length_hospitalization = paste0('median: ', median(orig_len_hosp),
                                              ', IQR: (', round(IQR(orig_len_hosp), digits = 2),
                                              '), min,max: [', min(orig_len_hosp), ',', max(orig_len_hosp),
                                              '], mean= ', round(mean(orig_len_hosp), digits = 2),
                                              ', SD=', round(sd(orig_len_hosp), digits = 2))) %>%
    t() %>%
    as.data.frame()
  colnames(continuous_total_summary) <- 'total'
  continuous_total_summary$variableName <- rownames(continuous_total_summary)
  rownames(continuous_total_summary) <- NULL

  # if the data does not contain all variants, add in the columns here
  if(!'Alpha' %in% colnames(continuous_summary)){continuous_summary$Alpha <- NA}
  if(!'Delta' %in% colnames(continuous_summary)){continuous_summary$Delta <- NA}
  if(!'Omicron' %in% colnames(continuous_summary)){continuous_summary$Omicron <- NA}

  continuous_summary <- left_join(continuous_summary, continuous_total_summary) %>%
    rename( 'categories' = 'variableName')

  print("continuous_total_summary created")
  ## add the kruskal p.value
  stats_kruskal <- mainTable %>%
    dplyr::select( age, length_hospitalization = len_hospitalisation, variant_misc ) %>%
    unique() %>%
    tidyr::pivot_longer( cols = c(age, length_hospitalization), names_to = 'categories') %>%
    dplyr::group_by( categories )

  # only estimate the p-value if ar least 2 variant groups are present.
  if(n_distinct(complete_df$variant_misc) >= 2){
    stats_kruskal <- stats_kruskal %>%
      do(tidy(kruskal.test(x = .$value, g = .$variant_misc))) %>%
      dplyr::mutate( p.value = round( p.value, 3)) %>%
      select( categories, p.value ) %>%
      unique()

  }else{
    stats_kruskal <- stats_kruskal %>%
      mutate(p.value = NA) %>%
      select( categories, p.value ) %>%
      unique()
  }


  continuous_summary <- left_join( continuous_summary, stats_kruskal )


  ##### add the race if available
  if( raceAvailable == TRUE ){

    raceValuesPresent <- unique( mainTable$race_4ce)

    ## estimate the p-value (fisher test) if:
    ### - at least one value for the variant / race (n_distinct_subgroup)
    ### - at least 2 variants are present (variants_present)
    ### - not all the values are the same (n_distinct_values)
    race_fisher_df <- mainTable %>%
      select(race_4ce, variant_misc, patient_num) %>%
      unique() %>%
      mutate(value = 1) %>%
      pivot_wider(id_cols = c(patient_num, variant_misc), names_from = race_4ce, values_fill = 0) %>%
      pivot_longer(cols = all_of( raceValuesPresent ), names_to = 'categories') %>%
      group_by(categories, variant_misc) %>%
      mutate(n_distinct_subgroup = length(unique(patient_num))) %>%
      ungroup() %>%
      group_by(categories) %>%
      mutate( n_distinct_values = length(unique( value )),
              p.value = ifelse( n_distinct_subgroup > 1 & n_distinct_values > 1 & variants_present, round( fisher.test( value, variant_misc )$p.value, 3), NA))%>%
      select( categories, p.value ) %>%
      unique()

    allRaces <- c('white', 'other', 'black', 'asian', 'no_information', 'american_indian')
    ### to test
    ## allRaces <- c('white', 'other', 'black', 'asian', 'no_information', 'american_indian', "test")

    missingRaces <- allRaces[! allRaces %in% raceValuesPresent ]

    if(length( missingRaces) != 0){
      for( i in 1:length( missingRaces) ){
        categories <- c(missingRaces[i])
        p.value <- NA
        new_row <- data.frame(categories, p.value)
        race_fisher_df <- rbind( race_fisher_df, new_row)
      }
    }

    # get counts and percentages
    race_counts <- mainTable %>%
      select(race_4ce, variant_misc, patient_num) %>%
      unique() %>%
      group_by(race_4ce, variant_misc) %>%
      mutate(N = n_distinct(patient_num),
             n_obfuscated = ifelse( N > obfuscation_threshold | isFALSE( obfuscation_threshold), N, 0.5),
             perc = round((n_obfuscated / total_n_patients) * 100, digits = 2),
             value = paste0(n_obfuscated, ' (', perc, '%)')) %>%
      ungroup() %>%
      select(-patient_num) %>%
      unique() %>%
      group_by(race_4ce) %>%
      mutate(total = paste0(sum(n_obfuscated), ' (', round((sum(n_obfuscated) / total_n_patients) * 100, digits = 2), '%)')) %>%
      select('categories' = race_4ce, variant_misc, total, value) %>%
      pivot_wider(id_cols = c(categories, total), names_from = variant_misc)

    if(length( missingRaces) != 0){
      for( i in 1:length( missingRaces) ){
        categories <- c(missingRaces[i])
        total <- "0 (0%)"
        Alpha <- "0 (0%)"
        Omicron <- "0 (0%)"
        Delta <- "0 (0%)"
        new_row <- data.frame(categories, total, Alpha, Omicron, Delta)
        race_counts <- rbind( race_counts, new_row)
      }
    }

    # merge
    racedf <- race_counts %>% left_join(race_fisher_df)

    # if the data does not contain all variants, add in the columns here
    if(!'Alpha' %in% colnames(racedf)){racedf$Alpha <- NA}
    if(!'Delta' %in% colnames(racedf)){racedf$Delta <- NA}
    if(!'Omicron' %in% colnames(racedf)){racedf$Omicron <- NA}

    # change NA by 0 (0%)
    racedf[ is.na( racedf$Alpha ), ]$Alpha <- "0 (0%)"
    racedf[ is.na( racedf$Delta ), ]$Delta <- "0 (0%)"
    racedf[ is.na( racedf$Omicron ), ]$Omicron <- "0 (0%)"
    racedf[ is.na( racedf$total ), ]$total <- "0 (0%)"
  }


  # combine all summaries
  if( raceAvailable == TRUE ){
    output_table1 <- rbind( continuous_summary, racedf, output_table1_cat_with_stats ) %>%
      select(categories, Alpha, Delta, Omicron, 'Total' = 'total', p.value)
  }else{
    output_table1 <- rbind( continuous_summary, output_table1_cat_with_stats ) %>%
      select(categories, Alpha, Delta, Omicron, 'Total' = 'total', p.value)
  }

  # reorder columns
  output_table1 <- output_table1 %>% select(categories, Alpha, Delta, Omicron, Total, p.value)

  # add n to column names
  colnames_df <- mainTable %>%
    group_by(variant_misc) %>%
    summarise(N = n_distinct(patient_num)) %>%
    ungroup()
  if(!'Alpha' %in% colnames_df$variant_misc){colnames_df <- rbind(colnames_df, data.frame('variant_misc' = 'Alpha', 'N' = 0))}
  if(!'Delta' %in% colnames_df$variant_misc){colnames_df <- rbind(colnames_df, data.frame('variant_misc' = 'Delta', 'N' = 0))}
  if(!'Omicron' %in% colnames_df$variant_misc){colnames_df <- rbind(colnames_df, data.frame('variant_misc' = 'Omicron', 'N' = 0))}

  colnames_df <- rbind(colnames_df, data.frame('variant_misc' = 'Total', 'N' = sum(colnames_df$N)))
  colnames_df <- colnames_df %>%
    mutate(pasted_names = paste0(variant_misc, ' (n = ', N, ')'))

  colnames(output_table1)[c(2,3,4,5)] <- colnames_df$pasted_names

  # export table
  write.table(x = output_table1, file = paste0(dir.output, currSiteId, '_table1.txt'), sep="\t", quote = FALSE, row.names = FALSE)
  save(output_table1, file = paste0(dir.output, "/outputTest.RData") )

  # return the final output table
  return( output_table1 )


}
