#' Function to get an overview of the MISC patients characteristics
#' (summary of age and sex ratio)
#'
#' Given the \code{data.frame} output generated by the \code{allFilesInOne} function
#' generates as output multiple \code{data.frame} and plots with the number of MISC
#' cases by wave and: age and sex ratio per wave
#'
#' @param integrated_df The data.frame generated by the \code{allFilesInOne} function.
#' @param output_plot By default \code{FALSE}. Change it to \code{TRUE} to get a barplot output.
#' @param output_df By default \code{TRUE}. Change it to \code{FALSE} to not to get the counts as a data.frame.
#' @param cbPalette Color palette to use for the plots (set up by default)
#' @param verbose By default \code{FALSE}. Change it to \code{TRUE} to get an on-time log from the function.
#' @return Multiple objects of class \code{data.frame} with the counts, and the plots when output_plot is set to TRUE.
#' @examples
#'
#' casesCounts <- misc_overview(
#'               integrated_df = misc_complete,
#'               output_plot = FALSE,
#'               output_df   = TRUE
#'              )
#' @export misc_overview
#'

misc_overview <- function( integrated_df, output_plot = FALSE, output_df = TRUE, cbPalette = cbPalette, verbose ){

  if( verbose == TRUE){
    print("Estimating the sex ratio per wave")
  }

  misc_sex_ratio <- integrated_df %>%
    dplyr::group_by( variant_misc, sex ) %>%
    dplyr::summarise( n =  length(unique(patient_num))) %>%
    dplyr::group_by( variant_misc ) %>%
    dplyr::mutate( ratio = n/sum(n))

  if( verbose == TRUE){
    print("Estimating the age distribution per wave")
  }

  misc_age_distribution <- integrated_df %>%
    dplyr::group_by( variant_misc ) %>%
    dplyr::summarize(min = min(age),
              q1 = quantile(age, 0.25),
              median = median(age),
              mean = mean(age),
              q3 = quantile(age, 0.75),
              max = max(age))

  print("#### Sex ratio")
  print( misc_sex_ratio )

  print("#### Age distribution")
  print( misc_age_distribution )


  if( output_df == TRUE ){
    ## Save the generated file with the counts as part of the outputs
    write.table( x         = misc_age_distribution,
                 file      = file.path(dir.output,paste0(currSiteId, "_MISCpatientAgeDistribution.txt")),
                 col.names = TRUE,
                 row.names = FALSE,
                 quote     = FALSE,
                 sep       = "\t" )
    write.table( x         = misc_sex_ratio,
                 file      = file.path(dir.output,paste0(currSiteId, "_MISCpatientSexRatio.txt")),
                 col.names = TRUE,
                 row.names = FALSE,
                 quote     = FALSE,
                 sep       = "\t" )
  }

  ###
  if( output_plot == TRUE ){

    ### sex ratio plot barplot
    misc_sex_ratio_plot <-ggplot2::ggplot(misc_sex_ratio, aes(fill=variant_misc, y=n, x=sex)) +
      geom_bar(position="dodge", stat="identity") +
      scale_fill_manual( values = cbPalette) +
      ggtitle("Sex ratio in MISC patients per wave") +
      xlab("Number of MISC patients") + ylab("Sex") +
      theme_bw() +
      theme(plot.title = element_text(hjust = 0.5))

    ggplot2::ggsave(filename=file.path(dir.output,paste0(currSiteId, "_misc_sex_ratio_plot.png")),plot=print(misc_sex_ratio_plot))

    ## age distribution plot
    misc_age_dsitribution_plot <- integrated_df %>%
      dplyr::group_by( variant_misc ) %>%
      ggplot(aes(variant_misc, age))+
      geom_boxplot(aes(fill=variant_misc), position = "dodge") +
      scale_fill_manual( values = cbPalette) +
      ggtitle("Age distribution in MISC patients per wave") +
      xlab("Age") + ylab("Variant") +
      theme_bw() +
      theme(plot.title = element_text(hjust = 0.5))
    ggplot2::ggsave(filename=file.path(dir.output,paste0(currSiteId, "_misc_age_dsitribution_plot.png")),plot=print(misc_age_dsitribution_plot))

  }





}


