#' Function to get an overview of the MISC patients characteristics
#' (summary of age and sex ratio, summary of ICU cases and length of
#' hospitalization during the MISC admission)
#'
#' Given the \code{data.frame} output generated by the \code{allFilesInOne} function
#' generates as output multiple \code{data.frame} and plots with the number of MISC
#' cases by wave and: age and sex ratio per wave, ICU cases and length of hospitalization
#'
#' @param integrated_df The data.frame generated by the \code{allFilesInOne} function.
#' @param obfuscation_threshold FALSE if no obfuscation is needed, the numeric value when there is obfuscation
#' @param output_plot By default \code{FALSE}. Change it to \code{TRUE} to get a barplot output.
#' @param output_df By default \code{TRUE}. Change it to \code{FALSE} to not to get the counts as a data.frame.
#' @param cbPalette Color palette to use for the plots (set up by default)
#' @param verbose By default \code{FALSE}. Change it to \code{TRUE} to get an on-time log from the function.
#' @return Multiple objects of class \code{data.frame} with the counts, and the plots when output_plot is set to TRUE.
#' @examples
#'
#' casesCounts <- misc_overview(
#'               integrated_df = misc_complete,
#'               output_plot = FALSE,
#'               output_df   = TRUE
#'              )
#' @export misc_overview
#'

misc_overview <- function( integrated_df, obfuscation_threshold, dir.output, output_plot = FALSE, output_df = TRUE, cbPalette = cbPalette, verbose ){

  currSiteId <- unique( integrated_df$siteid )

  if( verbose == TRUE){
    print("Estimating the sex ratio per wave")
  }


  misc_sex_ratio <- integrated_df %>%
    dplyr::group_by( variant_misc, sex ) %>%
    dplyr::summarise( n =  length(unique(patient_num))) %>%
    dplyr::group_by( variant_misc ) %>%
    dplyr::mutate( ratio = n/sum(n)) %>%
    dplyr::select( -n )

  if( verbose == TRUE){
    print("Estimating the age distribution per wave")
  }

  misc_age_distribution <- integrated_df %>%
    dplyr::select( patient_num, age, variant_misc) %>%
    unique() %>%
    dplyr::group_by( variant_misc ) %>%
    dplyr::summarize(min = min(age),
              q1 = quantile(age, 0.25),
              median = median(age),
              mean = mean(age),
              q3 = quantile(age, 0.75),
              sd = sd(age),
              max = max(age))

  print("#### Sex ratio")
  print( misc_sex_ratio )

  print("#### Age distribution")
  print( misc_age_distribution )

  ### estimate the length of first hospitalization and MISC patients in the ICU during first hospitalization per wave
  # filter to focus on the first hospitalization
  first_hospitalization <- integrated_df %>%
    dplyr::filter( n_hospitalisation == 1 )

  ## ICU
  misc_icu <- first_hospitalization %>%
    filter( in_icu == 1) %>%
    dplyr::group_by( variant_misc ) %>%
    dplyr::summarise( icu_patients = length(unique(patient_num))) %>%
    dplyr::mutate( var = "ICU",
                   icu_patients = ifelse( icu_patients > obfuscation_threshold | isFALSE( obfuscation_threshold), icu_patients, 0.5))

  print("#### ICU cases")
  print( misc_icu )

  ### length hospitalization
  hospitalization_length <- first_hospitalization %>%
    dplyr::select( patient_num, len_hospitalisation, variant_misc) %>%
    unique() %>%
    dplyr::group_by( variant_misc ) %>%
    dplyr::summarize(min = min(len_hospitalisation),
                     q1 = quantile(len_hospitalisation, 0.25),
                     median = median(len_hospitalisation),
                     mean = mean(len_hospitalisation),
                     q3 = quantile(len_hospitalisation, 0.75),
                     sd = sd(len_hospitalisation),
                     max = max(len_hospitalisation))
  print("#### Length of the MISC hospitalization")
  print( hospitalization_length )

  dir.output.qc <- paste0(dir.output, "/QC/")
  if (! dir.output.qc %in% list.dirs()) dir.create(dir.output.qc)

  dir.output.figures <- paste0(dir.output, "/figures/")
  if (! dir.output.figures %in% list.dirs()) dir.create(dir.output.figures)



  if( output_df == TRUE ){
    ## Save the generated file with the counts as part of the outputs
    write.table( x         = misc_age_distribution,
                 file      = file.path(dir.output.qc,paste0(currSiteId, "_MISCpatientAgeDistribution.txt")),
                 col.names = TRUE,
                 row.names = FALSE,
                 quote     = FALSE,
                 sep       = "\t" )
    write.table( x         = misc_sex_ratio,
                 file      = file.path(dir.output.qc,paste0(currSiteId, "_MISCpatientSexRatio.txt")),
                 col.names = TRUE,
                 row.names = FALSE,
                 quote     = FALSE,
                 sep       = "\t" )
    write.table( x         = misc_icu,
                 file      = file.path(dir.output.qc,paste0(currSiteId, "_MISCpatientICU.txt")),
                 col.names = TRUE,
                 row.names = FALSE,
                 quote     = FALSE,
                 sep       = "\t" )
    write.table( x         = hospitalization_length,
                 file      = file.path(dir.output.qc,paste0(currSiteId, "_MISChospitalization_length.txt")),
                 col.names = TRUE,
                 row.names = FALSE,
                 quote     = FALSE,
                 sep       = "\t" )
  }

  ###
  if( output_plot == TRUE ){

    ### sex ratio plot barplot
    # misc_sex_ratio_plot <-ggplot2::ggplot(misc_sex_ratio, aes(fill=variant_misc, y=ratio, x=sex)) +
    #   geom_bar(position="dodge", stat="identity") +
    #   scale_fill_manual( values = cbPalette) +
    #   ggtitle("Sex ratio in MISC patients per wave") +
    #   xlab("Sex") + ylab("Ratio") +
    #   theme_bw() +
    #   theme(plot.title = element_text(hjust = 0.5))
    #
    # ggplot2::ggsave(filename=file.path(dir.output,paste0(currSiteId, "_misc_sex_ratio_plot.png")),plot=print(misc_sex_ratio_plot))

    ## age distribution plot
    misc_age_dsitribution_plot <- integrated_df %>%
      dplyr::group_by( variant_misc ) %>%
      ggplot(aes(variant_misc, age))+
      geom_boxplot(aes(fill=variant_misc), position = "dodge") +
      scale_fill_manual( values = cbPalette) +
      ggtitle("Age distribution in MISC patients per wave") +
      xlab("Variant") + ylab("Age") +
      theme_bw() +
      theme(plot.title = element_text(hjust = 0.5))
    ggplot2::ggsave(filename=file.path(dir.output.figures,paste0(currSiteId, "_misc_age_dsitribution_plot.png")),plot=print(misc_age_dsitribution_plot))

    ## icu cases plot
    misc_icu_plot <- ggplot(misc_icu, aes(fill=variant_misc, y=icu_patients, x=var)) +
      geom_bar(position="dodge", stat="identity") +
      scale_fill_manual( values = cbPalette)+
      ggtitle("MISC patients in the ICU per wave") +
      xlab("") + ylab("Number of MISC patients") +
      theme_bw() +
      theme(plot.title = element_text(hjust = 0.5))
    ggplot2::ggsave(filename=file.path(dir.output.figures,paste0(currSiteId, "_misc_icu_plot.png")),plot=print(misc_icu_plot))

    ## length of hospitalization distribution plot
    misc_hosp_length_dsitribution_plot <- first_hospitalization %>%
      dplyr::group_by( variant_misc ) %>%
      ggplot(aes(variant_misc, len_hospitalisation))+
      geom_boxplot(aes(fill=variant_misc), position = "dodge") +
      scale_fill_manual( values = cbPalette) +
      ggtitle("Hospitalization length distribution in MISC patients per wave") +
      xlab("Variant") + ylab("Days hospitalized") +
      theme_bw() +
      theme(plot.title = element_text(hjust = 0.5))
    ggplot2::ggsave(filename=file.path(dir.output.figures,paste0(currSiteId, "_misc_hosp_length_dsitribution_plot.png")),plot=print(misc_hosp_length_dsitribution_plot))
  }
}


