#' Function to get table 1 categorical variables

#' Given the \code{data.frame} output generated by the \code{allFilesInOne} function
#' generates as output the table 1 for the manuscript for categorical variables
#'
#' @param complete_df The data.frame generated by the \code{allFilesInOne} function.
#' @param obfuscation_threshold FALSE if no obfuscation is needed, the numeric value when there is obfuscation
#' @param currSiteId Site ID
#' @param verbose By default \code{FALSE}. Change it to \code{TRUE} to get an on-time log from the function.
#' @return Table 1 categorical variables for the manuscript.
#' @examples
#'
#' t1_cat <- misc_table1_cat(
#'               complete_df,
#'               currSiteId,
#'               obfuscation_threshold,
#'               verbose
#'              )
#' @export misc_table1_cat
#'
#'
#'
misc_table1_cat <- function(complete_df, obfuscation_threshold, currSiteId, dir.output, raceAvailable, verbose){

  clinicalChar <- read.delim('inst/extdata/clinicalCharacteristics.txt')
  total_n_patients <- length(unique(complete_df$patient_num))

  mainTable <- complete_df %>%
    filter( n_hospitalisation == 1 ) %>%
    select( patient_num, variant_misc, len_hospitalisation, age, sex, in_icu, dead ) %>%
    unique() %>%
    group_by( patient_num ) %>%
    mutate( in_icu = ifelse( sum( in_icu )>=1, 1, 0),
            dead = ifelse( sum( dead )>=1, 1, 0)) %>%
    ungroup() %>%
    select( patient_num, variant_misc, len_hospitalisation, age, sex, in_icu, dead ) %>%
    unique()

  #add race if available
  if( raceAvailable == TRUE ){
    mainTable <- left_join( mainTable, race_raw %>% select( patient_num, race_4ce), by="patient_num")
  }

  # at category level
  clin_var_category <- complete_df %>%
    filter( concept_code %in% clinicalChar$concept_code ) %>%
    left_join( clinicalChar, by = "concept_code") %>%
    mutate( value = 1 ) %>%
    select( patient_num, concept_code, category, value) %>%
    unique() %>%
    spread(key = category, value =  value, fill = 0) %>%
    select( -concept_code) %>%
    unique() %>%
    group_by( patient_num ) %>%
    summarise(across(everything(), sum)) %>%
    unique()

  #at variable name level
  clin_var_variable_name <- complete_df %>%
    filter( concept_code %in% clinicalChar$concept_code ) %>%
    left_join( clinicalChar, by = "concept_code") %>%
    mutate( value = 1 ) %>%
    select( patient_num, concept_code, variableName, value) %>%
    unique() %>%
    spread(key = variableName, value =  value, fill = 0) %>%
    select( -concept_code) %>%
    unique() %>%
    group_by( patient_num ) %>%
    summarise(across(everything(), sum)) %>%
    unique()

  # merge both
  clin_var <- merge( clin_var_category, clin_var_variable_name)

  ### add the new variables and
  mainTable <- mainTable %>%
    dplyr::left_join( clin_var, by = "patient_num") %>%
    replace(is.na(.), 0)

  ## any non-present variable as empty column all with 0
  varsNoPatients <- clinicalChar %>%
    dplyr::select( category ) %>%
    unique( ) %>%
    dplyr::filter(! category %in% colnames( mainTable ))

  if( length( varsNoPatients$category) != 0){
    for( i in 1:length( varsNoPatients$category )){
      mainTable[ varsNoPatients$category[i]] <- 0
    }
  }

  varsNoPatientsVarLevel <- clinicalChar %>%
    dplyr::select( variableName ) %>%
    unique( ) %>%
    dplyr::filter(! variableName %in% colnames( mainTable ))

  if( length( varsNoPatientsVarLevel$variableName) != 0){
    for( i in 1:length( varsNoPatientsVarLevel$variableName )){
      mainTable[ varsNoPatientsVarLevel$variableName[i]] <- 0
    }
  }




  #re-pivot it
  long_table <- mainTable %>%
    tidyr::pivot_longer(
      cols = c(6,7,9:ncol(mainTable)),
      names_to = "categories",
      values_to = "value")



  ## estimate the p-value (fisher test)
  fisherTest <- long_table %>%
    group_by( categories ) %>%
    mutate( n_distinct_values = length(unique( value )),
            p.value = ifelse( n_distinct_values > 1, round( fisher.test( value, variant_misc )$p.value, 3), NA))%>%
            #p.value = round( fisher.test( value, variant_misc )$p.value, 3) ) %>%
    select( categories, p.value ) %>%
    unique()

  ## estimate the N and percentage per category
  counts_percentages <- long_table %>%
    group_by( variant_misc ) %>%
    mutate(total_n = n_distinct(patient_num)) %>%
    filter( value == 1 ) %>%
    group_by(categories, variant_misc) %>%
    summarise(n = n_distinct(patient_num),
              n_obfuscated = ifelse( n > obfuscation_threshold | isFALSE( obfuscation_threshold), n, 0.5),
              perc = (n_obfuscated / total_n) * 100) %>%
    unique() %>%
    select(-n_obfuscated)

  counts_percentages_total <- long_table %>%
    filter( value == 1 ) %>%
    group_by(categories ) %>%
    summarise(n = n_distinct(patient_num),
              n_obfuscated = ifelse( n > obfuscation_threshold | isFALSE( obfuscation_threshold), n, 0.5),
              perc = (n_obfuscated / total_n_patients) * 100) %>%
    unique() %>%
    select(-n_obfuscated) %>%
    mutate( variant_misc = "total")

  #combine both
  counts_percentages_combined <- rbind(counts_percentages, counts_percentages_total )

  # pivot counts_percentages with combined n / percentage cells
  output_table1_cat_with_stats <- counts_percentages_combined %>%
    mutate(n_perc = paste0(n, ' (', round(perc, digits = 2), '%)')) %>%
    select(-n, -perc) %>%
    unique() %>%
    tidyr::pivot_wider(names_from = variant_misc, values_from = n_perc, values_fill = '0 (0%)') %>%
    right_join( fisherTest )

  # order rows
  ordered_rows <- c('overweight', 'obesity',
                    'fatigue_asthenia', 'rash_erythema',
                    'GI SYMPTOMS', 'abdominal pain', 'nausea_vomiting', 'diarrhea_enteritis_ileitis', 'apendicitis_peritonitis',
                    'RESPIRATORY SYMPTOMS', 'cough', 'rhinitis rhinorrhea', 'sore throat', 'tachypnea', 'dyspnea_shortness of breath',
                    'CARDIOVASCULAR SYMPTOMS', 'chest pain', 'palpitations', 'peripheral edema','hypotension', 'pre-syncope_syncope','ventricular dysfunction', 'heart failure', 'shock',
                    'NEUROLOGIC SYMPTOMS', 'headache', 'confusion', 'irritability', 'seizures', 'muscle weakness', 'encephalopathy_meningoencephalitis', 'lethargy', 'stroke',
                    'RENAL INVOLVEMENT', 'kidney dysfunction', 'acute renal failure',
                    'LIVER INVOLVEMENT', 'hepatitis', 'liver dysfunction', 'hepatic failure',
                    'Kawasaki')

  # reorder combined df
  output_table1_cat_with_stats <- output_table1_cat_with_stats %>%
    filter( categories %in% ordered_rows ) %>%
    mutate(categories =  factor(categories, levels = ordered_rows)) %>%
    arrange(categories)

  # change NA by 0 (0%)
  output_table1_cat_with_stats[ is.na( output_table1_cat_with_stats$Alpha ), ]$Alpha <- "0 (0%)"
  output_table1_cat_with_stats[ is.na( output_table1_cat_with_stats$Delta ), ]$Delta <- "0 (0%)"
  output_table1_cat_with_stats[ is.na( output_table1_cat_with_stats$Omicron ), ]$Omicron <- "0 (0%)"
  output_table1_cat_with_stats[ is.na( output_table1_cat_with_stats$total ), ]$total <- "0 (0%)"

  # export table
  write.csv(output_table1_cat_with_stats, paste0(dir.output, currSiteId, '_table1_cat.csv'), quote = FALSE, row.names = FALSE)

  # return the final output table
  return( output_table1_cat_with_stats )


}
