#' Function to get an additional table for future paper

#' Given the \code{data.frame} output generated by the \code{allFilesInOne} function
#' generates as output the extra table for future manuscripts
#'
#' @param complete_df The data.frame generated by the \code{allFilesInOne} function.
#' @param dir.input The path where the 2.2 MISC cohort files are located.
#' @param obfuscation_threshold FALSE if no obfuscation is needed, the numeric value when there is obfuscation
#' @param currSiteId Site ID
#' @param verbose By default \code{FALSE}. Change it to \code{TRUE} to get an on-time log from the function.
#' @return Extra table
#' @examples
#'
#' t_extra <- misc_extraTable(
#'               complete_df,
#'               currSiteId,
#'               obfuscation_threshold,
#'               verbose
#'              )
#' @export misc_extraTable
#'
#'
#'
misc_extraTable <- function(complete_df, obfuscation_threshold, currSiteId, dir.input, dir.output, raceAvailable, verbose){

  clinicalChar <- read.delim(system.file(paste0("extdata", .Platform$file.sep,
                                                "clinicalCharacteristics_paper2.txt"), package = "FourCePhase2.2MISC"), stringsAsFactors = FALSE)

  # remove dots from ICD codes to make sure if matches with all the sites
  clinicalChar$concept_code <- gsub("[.]", "", clinicalChar$concept_code)

  total_n_patients <- length(unique(complete_df$patient_num))
  print(paste0("Total MISC patients used as denominator for extra table: ", total_n_patients))

  mainTable <- complete_df %>%
    filter( n_hospitalisation == 1 ) %>%
    select( patient_num, variant_misc, len_hospitalisation, age, sex, in_icu, dead ) %>%
    unique() %>%
    group_by( patient_num ) %>%
    mutate( in_icu = ifelse( sum( in_icu )>=1, 1, 0),
            dead = ifelse( sum( dead )>=1, 1, 0)) %>%
    ungroup() %>%
    select( patient_num, variant_misc, len_hospitalisation, age, sex, in_icu, dead ) %>%
    unique()

  print("main table created")

  #add race if available
  if( raceAvailable == TRUE ){
    race_raw <- read.delim(file.path(dir.input, "/LocalPatientRace.csv"), sep = ",", skip = 0)
    mainTable <- left_join( mainTable, race_raw %>% select( patient_num, race_4ce), by="patient_num")
  }

  # remove dots from ICD codes in complete_df if any
  complete_df$concept_code <- gsub( "[.]", "", complete_df$concept_code )
  # at category level
  clin_var_category <- complete_df %>%
    filter( concept_code %in% clinicalChar$concept_code ) %>%
    left_join( clinicalChar, by = "concept_code") %>%
    mutate( value = 1 ) %>%
    select( patient_num, category, value) %>%
    unique() %>%
    spread(key = category, value =  value, fill = 0) %>%
    unique() %>%
    group_by( patient_num ) %>%
    summarise(across(everything(), sum)) %>%
    unique()

  print("clin_var_category created")

  #at variable name level
  clin_var_variable_name <- complete_df %>%
    filter( concept_code %in% clinicalChar$concept_code ) %>%
    left_join( clinicalChar, by = "concept_code") %>%
    mutate( value = 1 ) %>%
    select( patient_num, variableName, value) %>%
    unique() %>%
    spread(key = variableName, value =  value, fill = 0) %>%
    unique() %>%
    group_by( patient_num ) %>%
    summarise(across(everything(), sum)) %>%
    unique()
  print("clin_var_variable_name created")

  # merge both
  clin_var <- merge( clin_var_category, clin_var_variable_name)

  ### add the new variables and
  mainTable <- mainTable %>%
    dplyr::left_join( clin_var, by = "patient_num") %>%
    replace(is.na(.), 0)

  ## any non-present variable as empty column all with 0
  varsNoPatients <- clinicalChar %>%
    dplyr::select( category ) %>%
    unique( ) %>%
    dplyr::filter(! category %in% colnames( mainTable ))

  if( length( varsNoPatients$category) != 0){
    for( i in 1:length( varsNoPatients$category )){
      mainTable[ varsNoPatients$category[i]] <- 0
    }
  }

  varsNoPatientsVarLevel <- clinicalChar %>%
    dplyr::select( variableName ) %>%
    unique( ) %>%
    dplyr::filter(! variableName %in% colnames( mainTable ))

  if( length( varsNoPatientsVarLevel$variableName) != 0){
    for( i in 1:length( varsNoPatientsVarLevel$variableName )){
      mainTable[ varsNoPatientsVarLevel$variableName[i]] <- 0
    }
  }

  vars_of_interest <- c()
  for(i in 1:nrow(clinicalChar)) {

    if (!clinicalChar$category[i] %in% vars_of_interest) {vars_of_interest <- c(vars_of_interest, clinicalChar$category[i])}
    if (!clinicalChar$variableName[i] %in% vars_of_interest) {vars_of_interest <- c(vars_of_interest, clinicalChar$variableName[i])}
  }


  #re-pivot it
  long_table <- mainTable %>%
    tidyr::pivot_longer(
      cols = all_of(vars_of_interest),
      names_to = "categories",
      values_to = "value")

  print("long_table created")

  ## estimate the p-value (fisher test) if:
  ### - at least one value for the variant / category (n_distinct_subgroup)
  ### - at least 2 variants are present (variants_present)
  ### - not all the values are the same (n_distinct_values)
  variants_present <- n_distinct(long_table$variant_misc) >= 2
  fisherTest <- long_table %>%
    group_by(categories, variant_misc) %>%
    mutate(n_distinct_subgroup = length(unique(patient_num))) %>%
    ungroup() %>%
    group_by( categories ) %>%
    mutate( n_distinct_values = length(unique( value )),
            p.value = ifelse(  n_distinct_subgroup > 1 & n_distinct_values > 1 & variants_present, round( fisher.test( value, variant_misc )$p.value, 3), NA))%>%
    select( categories, p.value ) %>%
    unique()

  ## estimate the N and percentage per category
  counts_percentages <- long_table %>%
    group_by( variant_misc ) %>%
    mutate(total_n = n_distinct(patient_num)) %>%
    filter( value == 1 ) %>%
    group_by(categories, variant_misc) %>%
    summarise(n = n_distinct(patient_num),
              n_obfuscated = ifelse( n > obfuscation_threshold | isFALSE( obfuscation_threshold), n, 0.5),
              perc = (n_obfuscated / total_n) * 100) %>%
    unique() %>%
    select(-n_obfuscated)

  counts_percentages_total <- long_table %>%
    filter( value == 1 ) %>%
    group_by(categories ) %>%
    summarise(n = n_distinct(patient_num),
              n_obfuscated = ifelse( n > obfuscation_threshold | isFALSE( obfuscation_threshold), n, 0.5),
              perc = (n_obfuscated / total_n_patients) * 100) %>%
    unique() %>%
    select(-n_obfuscated) %>%
    mutate( variant_misc = "total")

  #combine both
  counts_percentages_combined <- rbind(counts_percentages, counts_percentages_total )

  # save the output as an RData file for meta-analysis before reformating
  counts_combined4meta = counts_percentages_combined %>%
    mutate( n = ifelse( n > obfuscation_threshold | isFALSE( obfuscation_threshold), n , 0.5)) %>%
    select( - perc )
  table_extra <- counts_combined4meta
  save(table_extra, file = paste0(dir.output, "/", currSiteId,"_tableExtra.RData") )

  # pivot counts_percentages with combined n / percentage cells
  output_table_extra_with_stats <- counts_percentages_combined %>%
    mutate(n_perc = paste0(n, ' (', round(perc, digits = 2), '%)')) %>%
    select(-n, -perc) %>%
    unique() %>%
    tidyr::pivot_wider(names_from = variant_misc, values_from = n_perc, values_fill = '0 (0%)') %>%
    right_join( fisherTest )

  print("output_table_extra_with_stats created")
  # order rows
  ordered_rows <- vars_of_interest

  # reorder combined df
  print(paste0("output_table_extra_with_stats has ", nrow(output_table_extra_with_stats), " number of rows"))
  print(paste0("the categories present in this table are: ", paste( output_table_extra_with_stats$categories, collapse = "; ")))

  output_table_extra_with_stats <- output_table_extra_with_stats %>%
    filter( categories %in% ordered_rows ) %>%
    mutate(categories =  factor(categories, levels = ordered_rows)) %>%
    arrange(categories)


  # if the data does not contain all variants, add in the columns here
  if(!'Alpha' %in% colnames(output_table_extra_with_stats)){output_table_extra_with_stats$Alpha <- NA}
  if(!'Delta' %in% colnames(output_table_extra_with_stats)){output_table_extra_with_stats$Delta <- NA}
  if(!'Omicron' %in% colnames(output_table_extra_with_stats)){output_table_extra_with_stats$Omicron <- NA}


  # change NA by 0 (0%)
  output_table_extra_with_stats[ is.na( output_table_extra_with_stats$Alpha ), ]$Alpha <- "0 (0%)"
  output_table_extra_with_stats[ is.na( output_table_extra_with_stats$Delta ), ]$Delta <- "0 (0%)"
  output_table_extra_with_stats[ is.na( output_table_extra_with_stats$Omicron ), ]$Omicron <- "0 (0%)"
  output_table_extra_with_stats[ is.na( output_table_extra_with_stats$total ), ]$total <- "0 (0%)"

    output_tableExtra <- output_table_extra_with_stats %>%
      select(categories, Alpha, Delta, Omicron, 'Total' = 'total', p.value)

  # reorder columns
    output_tableExtra <- output_tableExtra %>% select(categories, Alpha, Delta, Omicron, Total, p.value)

  # add n to column names
  colnames_df <- mainTable %>%
    group_by(variant_misc) %>%
    summarise(N = n_distinct(patient_num)) %>%
    ungroup()
  if(!'Alpha' %in% colnames_df$variant_misc){colnames_df <- rbind(colnames_df, data.frame('variant_misc' = 'Alpha', 'N' = 0))}
  if(!'Delta' %in% colnames_df$variant_misc){colnames_df <- rbind(colnames_df, data.frame('variant_misc' = 'Delta', 'N' = 0))}
  if(!'Omicron' %in% colnames_df$variant_misc){colnames_df <- rbind(colnames_df, data.frame('variant_misc' = 'Omicron', 'N' = 0))}

  colnames_df <- rbind(colnames_df, data.frame('variant_misc' = 'Total', 'N' = sum(colnames_df$N)))
  colnames_df <- colnames_df %>%
    mutate(pasted_names = paste0(variant_misc, ' (n = ', N, ')'))

  colnames(output_tableExtra)[c(2,3,4,5)] <- colnames_df$pasted_names

  # export table
  write.table(x = output_tableExtra, file = paste0(dir.output,'/',currSiteId, '_tableExtra.txt'), sep="\t", quote = FALSE, row.names = FALSE)

  # return the final output table
  return( output_tableExtra )


}
